[connections.snowflake]
account = "uv21880.eu-central-1"
user = "ICL_SIZING_WEB_APP_USER"
password = "wrop-grog7TECK_blit"
role = "ICL_SIZING_WEB_APP_ROLE"
warehouse = "ICL_SIZING_WEB_APP_WH"
database = "ICL_SIZING_WEB_APP"
schema = "DHAC_INGRESS"
client_session_keep_alive = true
